### ISSUE TITLE
[Generated by cli] Potential redudant packages that are not covered by nolyfill

### ISSUE THREAD

**Issue by jerry7536** [SukkaW/nolyfill#51]
### `call-bind`

```
$ pnpm why call-bind
```

**stdout**

```
Legend: production dependency, optional only, dev only

node-test@0.2.0 D:\code\Front\npm\node-test

dependencies:
vite-plugin-node-polyfills 0.17.0
└─┬ node-stdlib-browser 1.2.0
  ├─┬ assert 2.1.0
  │ ├── call-bind 1.0.2
  │ └─┬ util 0.12.5
  │   └─┬ is-typed-array 1.1.10
  │     └── call-bind 1.0.2
  └─┬ util 0.12.5
    └─┬ is-typed-array 1.1.10
      └── call-bind 1.0.2

```

seems to be solved at #24, but still report this

run with `npx nolyfill@latest install`

**Comment by SukkaW** [comment]
The target package should be `is-typed-array` and `assert`.

**Comment by ljharb** [comment]
I’m not sure what those can be replaced with; is-typed-array is the minimal code to detect typed array internal slots, and assert is a browser polyfill for a node core module.

**Comment by ljharb** [comment]
that relies on unmodified builtins tho, which is not robust. call-bind is necessary there.

assert in core has changed plenty, and the assert package will eventually catch up - but I’m saying i don’t see the point of replacing it, and I’m not sure what you’d replace it with unless you reimplement the entire thing here (which, to match node, *must* be robust in a call-bind sense)

**Comment by SukkaW** [comment]
> lol k, not sure what to say to that one then. the reason it allows it is legacy consistency, not because you should pretend your code is running in a safe environment.

Considering that the installation size of `call-bind` is **189 KiB**, I'd (and I believe most of the developers) rather believe the code is running in a safe environment.

**Comment by SukkaW** [comment]
`assert` and `is-typed-array` are released in `nolyfill@1.0.26`.

**Comment by JounQin** [comment]
This is the most ridiculous reason I've heard that you don't trust you're running in a safe environment. LOL.

**Comment by ljharb** [comment]
That’s a lot of unwarranted hostility - there does not exist a safe environment, and I’m surprised you still labor under that delusion given your experience.

**Comment by JounQin** [comment]
> there does not exist a safe environment

Yes, and

> You can't be a gateway for everyone and everywhere. No human developer writes codes like that.

**Comment by JounQin** [comment]
What you should do is upgrading to latest safer environment instead of hacking and patching.

**Comment by JounQin** [comment]
> I’m surprised you still labor under that delusion given your experience.

Same for you.

**Comment by JounQin** [comment]
That's how programming works.

**Comment by JounQin** [comment]
@ljharb I didn't want to argument anymore actually. But I just noticed that you lockes the conversation and hidden my comments at https://github.com/browserify/node-util/pull/62#issuecomment-1876489559

That's really disappointing, again.

All developers there and here are all open to discuss, but you aren't.

You are the meanest developer I've seen, you're just living in your own world, and refuse any different advices. What's worse is that you have the dominance in js community, a lot of projects and developers are trusting you, giving you the admin permissions.

But what you have done? You put your shit es-shims in every projects which you have admin permission. Yes, they are shit for the whole js community. You're expanding the `node_modules` black hole. I don't see any value of them coming with `core-js` for compatibility.

You refuse any kind of breaking change. A lot of good features can not be implemented due to this. You're so opinionated that you ignore all against from the community. You protect the imagined little users and give up the practical users.

You're a stubborn, paranoid old man in my eyes.

**Comment by ljharb** [comment]
@JounQin again, you're being excessively hostile and it's just not warranted. I understand that you don't like some of my decisions, but that doesn't make them wrong or harmful, nor does it justify childish personal attacks.

You may want to consider that the reason I have the influence I have is because of the value I provide. New ideas aren't better just because they're new.

Please be aware that your conduct would get you banned from virtually any project with a CoC - this project may not have one - and I wouldn't want to see you run into that problem elsewhere, so I hope you take my advice under consideration.

**Comment by JounQin** [comment]
> you're being excessively hostile and it's just not warranted

Again, you're hurting the community, that makes sense to me.

> but that doesn't make them wrong or harmful, nor does it justify childish personal attacks.

It's harmful IMO. And it's not personal grudge. I'm just posting what you have done to the whole community, whether you like it or not.

> Please be aware that your conduct would get you banned from virtually any project with a CoC

That's why I said I didn't want to argument anymore previously, but what have you done? You chose to lock the conversation and hidden my comments, pretending they're not existed.

> I hope you take my advice under consideration.

I won't. I love coding, and I hate shit codes.

**Comment by wojtekmaj** [comment]
While I am certainly one of the people who most strongly disagrees with @ljharb's opinions, I must defend him - not his code, but him personally, because this discussion got personal. And I don't think it's a good idea. Let's keep the conversation civil please.

**Comment by wojtekmaj** [comment]
It's obvious that no one is going to let go here as the opinions are simply too strongly held. In the light of that, I think that:

Paradoxically, this disagreement may end up being a net positive for the industry. Projects like nolyfill may have a bigger positive impact on the entire industry than @ljharb letting go.

Jordan's certainly not the only person using polyfills (knowingly or not - doesn't matter, it's still a polyfill in your node_modules).

Node continues development and sunsetting older Node versions. I expect the performance gap between the latest native implementations and the polyfills in question to only get wider. That's increasingly true now with the impact Bun has.

We need to also take into consideration that there are tons of unmaintained libraries that the industry depends on, too. Sometimes it may be extremely difficult to replace them with a modern version. The chain of dependencies is sometimes 10+ nodes long, and good luck convincing everyone to release a new major version.

So even if Jordan _would_ let go, this problem won't magically disappear. The entire industry would need to get on board, and it would still take YEARS to clean up everyone's node_modules.

Also:

No one stops anyone from forking the libraries @ljharb maintain. In fact, this has already happened e.g. with `eslint-plugin-i`.

For when it's not feasible, this is where nolyfill steps in. They can't stop @ljharb from doing what he does, but _he_ can't stop nolyfill from doing what _they_ think is right either.

**Comment by JounQin** [comment]
@wojtekmaj Thanks for your input, I was really mad at that time

> But I just noticed that you locked the conversation and hidden my comments at https://github.com/browserify/node-util/pull/62#issuecomment-1876489559

**Comment by alex-kinokon** [comment]
> That’s a lot of unwarranted hostility - there does not exist a safe environment, and I’m surprised you still labor under that delusion given your experience[.](https://github.com/SukkaW/nolyfill/issues/51#issuecomment-1878098538)

Complaining about hostility and then immediately follow up with a personal attack. Really?

**Comment by ljharb** [comment]
@alex-kinokon that's not a personal attack, it's a compliment.

**Comment by JounQin** [comment]
@alex-kinokon Take it easy. ❤️
