### ISSUE TITLE
Replace qs

### ISSUE THREAD

**Issue by gkiely** [SukkaW/nolyfill#70]
Imports 14 dependencies
https://npm.anvaka.com/#/view/2d/qs
https://github.com/ljharb/qs/issues/404

**Comment by gkiely** [comment]
Potential replacement: https://github.com/sindresorhus/query-string

https://npm.anvaka.com/#/view/2d/query-string

**Comment by mikkurogue** [comment]
All [14](https://voldephobia.rschristian.dev/?q=qs dependencies) are also authored by our friend lol... 

I'll see if I can find some time to find a replacement and do my part in cleaning.

**Comment by SukkaW** [comment]
Actually, we don't have to replace the entire `qs`.

https://npmgraph.js.org/?q=qs

![image](https://github.com/SukkaW/nolyfill/assets/40715044/c9d74e93-fbfb-436b-b5bc-5b95b6f40c80)

As you can see, the *toxic* dependency is the `side-channel` that brings all its friends.

And nolyfill already handles `side-channel` by providing `@nolyfill/side-channel`: https://github.com/SukkaW/nolyfill/tree/93c7c4aace6d8e51b4c734f4d6d84fe9d0df8a2b/packages/generated/side-channel

@mikkurogue This info should help you if you want to submit a PR to `qs` or create a fork!

I am going to close the issue since we already have `@nolyfill/side-channel`. But if `qs` introduce any other new toxic dependencies, feel free to create a new issue or ping me to re-open this one!

**Comment by gkiely** [comment]
@SukkaW in case you want to add, this package has support: https://github.com/payloadcms/qs-esm
